/* ============================================================
   Translations for UI + Spec labels
   ============================================================ */
const translations = {
  en: {
    subtitle: "X-Ray Inspection Systems – Product Comparison",
    introTitle: "Select a Model to View Specifications",
    introText: "Click any model card below to see its full technical details",
    footer: "© WIPOTEC GmbH – X-Ray Comparison Tool",
    placeholder: "Select a model above to see detailed specifications",
    noImage: "📷 Image not available",
    compareTrayLabel: "Compare:",
    compareEmpty: "— Select model —",
    compareNow: "Compare Now",
    compareClear: "Clear",
    compareTitle: "Specification Comparison",
    compareClose: "Close",
    compareAlert: "You can compare up to 3 models at a time. Please clear one first.",
    labels: {
      "Orientation": "Orientation",
      "Output Power": "Output Power",
      "HV Voltage (Infinitely variable)": "HV Voltage (Infinitely variable)",
      "HV Current (Infinitely variable)": "HV Current (Infinitely variable)",
      "Cooling System": "Cooling System",
      "Sensor Technology": "Sensor Technology",
      "Resolution": "Resolution",
      "Scanning Speed": "Scanning Speed",
      "Drive": "Drive",
      "Max. Transport Weight": "Max. Transport Weight",
      "Display": "Display",
      "Temperature Range": "Temperature Range",
      "Construction Frame": "Construction Frame",
      "IP Rating": "IP Rating",
      "Power Supply": "Power Supply",
      "SCCR": "SCCR",
      "Weight": "Weight",
      "Memory Capacity": "Memory Capacity",
      "Work Height": "Work Height",
      "Max. Product Height": "Max. Product Height",
      "Transport Length": "Transport Length",
      "Launch Year": "Launch Year",
      "Warranty & Service Contract Conditions": "Warranty & Service Contract Conditions"
    },
    values: {
      "Top-Down": "Top-Down",
      "Top-Down (Bulk Flow)": "Top-Down (Bulk Flow)",
      "Side View": "Side View",
      "Side View (Single Horizontal Beam)": "Side View (Single Horizontal Beam)",
      "Side View (Split-Beam)": "Side View (Split-Beam)",
      "Side View (Angle Beam)": "Side View (Angle Beam)",
      "Diode": "Diode",
      "Stainless Steel": "Stainless Steel",
      "Cabinet Fan": "Cabinet Fan",
      "Additional AC unit": "Additional AC unit",
      "Air-Water Cooling Unit": "Air-Water Cooling Unit",
      "Internal Closed Loop cooling": "Internal Closed Loop cooling",
      "With curtain": "With curtain",
      "W/o curtain": "W/o curtain",
      "Customized": "Customized",
      "Color TFT": "Color TFT",
      "touch screen": "touch screen",
      "Depending on options": "Depending on options",
      "Opt": "Opt"
    }
  },
  th: {
    subtitle: "ระบบตรวจสอบด้วยรังสีเอกซ์ – เปรียบเทียบรุ่น",
    introTitle: "เลือกรุ่นเพื่อดูรายละเอียด",
    introText: "คลิกรุ่นด้านล่างเพื่อดูข้อมูลทางเทคนิคทั้งหมด",
    footer: "© WIPOTEC GmbH – เครื่องมือเปรียบเทียบ X-Ray",
    placeholder: "เลือกรุ่นด้านบนเพื่อดูรายละเอียด",
    noImage: "📷 ไม่มีรูปภาพ",
    compareTrayLabel: "เปรียบเทียบ:",
    compareEmpty: "— เลือกรุ่น —",
    compareNow: "เปรียบเทียบเลย",
    compareClear: "ล้าง",
    compareTitle: "เปรียบเทียบสเปก",
    compareClose: "ปิด",
    compareAlert: "เปรียบเทียบได้ครั้งละไม่เกิน 3 รุ่น กรุณาล้างอันเก่าก่อน",
    labels: {
      "Orientation": "การติดตั้ง",
      "Output Power": "กำลังไฟออก",
      "HV Voltage (Infinitely variable)": "แรงดันสูง (ปรับได้ไม่จำกัด)",
      "HV Current (Infinitely variable)": "กระแสสูง (ปรับได้ไม่จำกัด)",
      "Cooling System": "ระบบระบายความร้อน",
      "Sensor Technology": "เทคโนโลยีเซนเซอร์",
      "Resolution": "ความละเอียด",
      "Scanning Speed": "ความเร็วสแกน",
      "Drive": "ระบบขับเคลื่อน",
      "Max. Transport Weight": "น้ำหนักสูงสุดที่รับได้",
      "Display": "หน้าจอแสดงผล",
      "Temperature Range": "ช่วงอุณหภูมิใช้งาน",
      "Construction Frame": "โครงสร้าง",
      "IP Rating": "มาตรฐาน IP",
      "Power Supply": "ไฟเลี้ยง",
      "SCCR": "SCCR",
      "Weight": "น้ำหนักเครื่อง",
      "Memory Capacity": "ความจุหน่วยความจำ",
      "Work Height": "ความสูงงาน",
      "Max. Product Height": "ความสูงสินค้าสูงสุด",
      "Transport Length": "ความยาวระบบลำเลียง",
      "Launch Year": "ปีที่เปิดตัว",
      "Warranty & Service Contract Conditions": "เงื่อนไขการรับประกันและสัญญาบริการ"
    },
    values: {
      "Top-Down": "ติดตั้งด้านบน",
      "Top-Down (Bulk Flow)": "ติดตั้งด้านบน (ระบบ Bulk)",
      "Side View": "ติดตั้งด้านข้าง",
      "Side View (Single Horizontal Beam)": "ติดตั้งด้านข้าง (ลำแสงเดี่ยวแนวนอน)",
      "Side View (Split-Beam)": "ติดตั้งด้านข้าง (ลำแสงแยก)",
      "Side View (Angle Beam)": "ติดตั้งด้านข้าง (ลำแสงเฉียง)",
      "Diode": "ไดโอด",
      "Stainless Steel": "สแตนเลส",
      "Cabinet Fan": "พัดลมตู้",
      "Additional AC unit": "ชุดปรับอากาศเพิ่มเติม",
      "Air-Water Cooling Unit": "ชุดระบายความร้อนด้วยน้ำ",
      "Internal Closed Loop cooling": "ระบบระบายความร้อนแบบปิดภายใน",
      "With curtain": "มีม่าน",
      "W/o curtain": "ไม่มีม่าน",
      "Customized": "ปรับแต่งได้",
      "Color TFT": "จอสี TFT",
      "touch screen": "ระบบสัมผัส",
      "Depending on options": "ขึ้นกับออปชัน",
      "Opt": "ออปชัน"
    }
  },
  zh: {
    subtitle: "X 射线检测系统 – 产品对比",
    introTitle: "选择型号查看规格",
    introText: "点击下方任意型号卡片查看完整技术参数",
    footer: "© WIPOTEC GmbH – X 射线对比工具",
    placeholder: "请选择上方型号以查看详细规格",
    noImage: "📷 无图片",
    compareTrayLabel: "对比：",
    compareEmpty: "— 选择型号 —",
    compareNow: "立即对比",
    compareClear: "清除",
    compareTitle: "规格对比",
    compareClose: "关闭",
    compareAlert: "一次最多对比 3 个型号，请先清除一个。",
    labels: {
      "Orientation": "安装方向",
      "Output Power": "输出功率",
      "HV Voltage (Infinitely variable)": "高压（无级可调）",
      "HV Current (Infinitely variable)": "高压电流（无级可调）",
      "Cooling System": "冷却系统",
      "Sensor Technology": "传感器技术",
      "Resolution": "分辨率",
      "Scanning Speed": "扫描速度",
      "Drive": "驱动系统",
      "Max. Transport Weight": "最大输送重量",
      "Display": "显示屏",
      "Temperature Range": "工作温度范围",
      "Construction Frame": "机架结构",
      "IP Rating": "防护等级",
      "Power Supply": "电源",
      "SCCR": "短路电流额定值",
      "Weight": "重量",
      "Memory Capacity": "存储容量",
      "Work Height": "工作高度",
      "Max. Product Height": "最大产品高度",
      "Transport Length": "输送长度",
      "Launch Year": "发布年份",
      "Warranty & Service Contract Conditions": "保修和服务合同条款"
    },
    values: {
      "Top-Down": "顶置式",
      "Top-Down (Bulk Flow)": "顶置式（散料流）",
      "Side View": "侧视式",
      "Side View (Single Horizontal Beam)": "侧视式（单水平束）",
      "Side View (Split-Beam)": "侧视式（分束）",
      "Side View (Angle Beam)": "侧视式（角束）",
      "Diode": "二极管",
      "Stainless Steel": "不锈钢",
      "Cabinet Fan": "机柜风扇",
      "Additional AC unit": "附加空调单元",
      "Air-Water Cooling Unit": "风冷-水冷单元",
      "Internal Closed Loop cooling": "内部闭环冷却",
      "With curtain": "带挡帘",
      "W/o curtain": "无挡帘",
      "Customized": "可定制",
      "Color TFT": "彩色 TFT",
      "touch screen": "触摸屏",
      "Depending on options": "取决于选项",
      "Opt": "选配"
    }
  }
};

/* ============================================================
   Model data — WIPOTEC
   ============================================================ */
const modelsWipotec = [
  {
    brand: "Wipotec",
    name: "SC-E 3000/4000", tag: "Top-Down",
    image: "img/SC-E-3000-4000.png",
    specs: {
      "Orientation": "Top-Down", "Output Power": "200 W",
      "HV Voltage (Infinitely variable)": "80 kV",
      "HV Current (Infinitely variable)": "3 mA",
      "Cooling System": "Cabinet Fan; Additional AC unit <span class='opt'>(Opt)</span>",
      "Sensor Technology": "Diode",
      "Resolution": "0.4 mm; 0.8 mm <span class='opt'>(Opt)</span>",
      "Scanning Speed": "50 m/min; 90 m/min <span class='opt'>(Opt)</span>",
      "Drive": "I-Mot3", "Max. Transport Weight": "10 kg",
      "Display": "15\" Color TFT w/ touch screen",
      "Temperature Range": "+5 to +35°C; +5 to +40°C <span class='opt'>(Opt)</span>",
      "Construction Frame": "Stainless Steel",
      "IP Rating": "IP65 (Cabinet fan on the back IP54)",
      "Power Supply": "230 Vac; 150 Vac <span class='opt'>(Opt)</span>",
      "SCCR": "5 kA", "Weight": "Approx. 400 kg", "Memory Capacity": "100",
      "Work Height": "750-850 / 850-950 mm",
      "Max. Product Height": "130 mm",
      "Transport Length": "800 / 1500 / 1800 mm"
    }
  },
  {
    brand: "Wipotec",
    name: "SC 30/40", tag: "Top-Down",
    image: "img/SC-30-40.png",
    specs: {
      "Orientation": "Top-Down", "Output Power": "200 W / 600 W",
      "HV Voltage (Infinitely variable)": "Diode 80 kV; VioX & DFX-Ray 75 kV",
      "HV Current (Infinitely variable)": "Diode 3 mA; VioX & DFX-Ray 10 mA",
      "Cooling System": "Cabinet Fan; Air-water cooling for 600W",
      "Sensor Technology": "Diode / VioX / DF",
      "Resolution": "Diode 0.4 mm; VioX 0.1 mm; DF 0.4 mm",
      "Scanning Speed": "Max. 120 m/min",
      "Drive": "I-Mot3", "Max. Transport Weight": "—",
      "Display": "15\" Color TFT w/ touch screen; 19\" <span class='opt'>(Opt)</span>",
      "Temperature Range": "+5 to +35°C; +5 to +40°C <span class='opt'>(Opt)</span>",
      "Construction Frame": "Stainless Steel",
      "IP Rating": "IP65 (Cabinet fan on the back IP54)",
      "Power Supply": "230 Vac", "SCCR": "5 kA",
      "Weight": "Approx. 400 kg", "Memory Capacity": "100",
      "Work Height": "750-850 / 750-900 / 800-950 / 900-1050 / 1000-1150 / 1100-1250 mm",
      "Max. Product Height": "With curtain 180 mm; W/o curtain 230 mm",
      "Transport Length": "Customized"
    }
  },
  {
    brand: "Wipotec",
    name: "SC-B 30", tag: "Top-Down",
    image: "img/SC-B-30.png",
    specs: {
      "Orientation": "Top-Down", "Output Power": "200 W",
      "HV Voltage (Infinitely variable)": "80 kV",
      "HV Current (Infinitely variable)": "3 mA",
      "Cooling System": "Cabinet Fan; Additional AC unit <span class='opt'>(Opt)</span>",
      "Sensor Technology": "Diode",
      "Resolution": "0.4 mm; 0.8 mm <span class='opt'>(Opt)</span>",
      "Scanning Speed": "Max. 70 m/min; Mass 6,000 kg/hr",
      "Drive": "I-Mot3", "Max. Transport Weight": "—",
      "Display": "15\" Color TFT w/ touch screen",
      "Temperature Range": "+5 to +35°C; +5 to +40°C <span class='opt'>(Opt)</span>",
      "Construction Frame": "Stainless Steel",
      "IP Rating": "IP65 (Cabinet fan on the back IP54)",
      "Power Supply": "230 Vac; 150 Vac <span class='opt'>(Opt)</span>",
      "SCCR": "5 kA", "Weight": "Approx. 500 kg", "Memory Capacity": "100",
      "Work Height": "670-730 / 750-850 / 850-950 / 950-1050 mm",
      "Max. Product Height": "Bulk height: 20 mm; Bulk width: 250 mm",
      "Transport Length": "1490 / 1790 mm"
    }
  },
  {
    brand: "Wipotec",
    name: "SC 2000", tag: "Top-Down",
    image: "img/SC-2000.png",
    specs: {
      "Orientation": "Top-Down", "Output Power": "150 W",
      "HV Voltage (Infinitely variable)": "50 kV",
      "HV Current (Infinitely variable)": "3 mA",
      "Cooling System": "Cabinet Fan; Additional AC unit <span class='opt'>(Opt)</span>",
      "Sensor Technology": "Diode", "Resolution": "0.4 mm",
      "Scanning Speed": "Max. 120 m/min",
      "Drive": "I-Mot3", "Max. Transport Weight": "—",
      "Display": "15\" Color TFT w/ touch screen",
      "Temperature Range": "+5 to +40°C",
      "Construction Frame": "Stainless Steel",
      "IP Rating": "IP65 (Cabinet fan on the back IP54)",
      "Power Supply": "230 Vac", "SCCR": "5 kA",
      "Weight": "Approx. 400 kg", "Memory Capacity": "100",
      "Work Height": "650-750 / 750-850 / 850-950 / 950-1050 mm",
      "Max. Product Height": "110 mm",
      "Transport Length": "700-2100 mm (by 100 mm incremental)"
    }
  },
  {
    brand: "Wipotec",
    name: "SC 5000/6000", tag: "Top-Down",
    image: "img/SC-30-40.png",
    specs: {
      "Orientation": "Top-Down", "Output Power": "600 W",
      "HV Voltage (Infinitely variable)": "60 kV or 75 kV",
      "HV Current (Infinitely variable)": "8 mA or 10 mA",
      "Cooling System": "Internal Closed Loop cooling",
      "Sensor Technology": "VioX - TDi", "Resolution": "VioX 0.1 mm",
      "Scanning Speed": "49 m/min (Depending on options)",
      "Drive": "I-Mot3", "Max. Transport Weight": "—",
      "Display": "15\" Color TFT w/ touch screen",
      "Temperature Range": "+5 to +40°C",
      "Construction Frame": "Stainless Steel",
      "IP Rating": "IP65 (Except for Air-Water cooled units)",
      "Power Supply": "400 Vac 3 Phase", "SCCR": "5 kA",
      "Weight": "—", "Memory Capacity": "100",
      "Work Height": "750-850 / 800-900 / 850-950 mm",
      "Max. Product Height": "—", "Transport Length": "Customized"
    }
  },
  {
    brand: "Wipotec",
    name: "SC-S 4000", tag: "Side View",
    image: "img/SC-S-4000.png",
    specs: {
      "Orientation": "Side View", "Output Power": "600 W",
      "HV Voltage (Infinitely variable)": "75 kV",
      "HV Current (Infinitely variable)": "8 mA; 10 mA (60 kV Machine)",
      "Cooling System": "Air-Water Cooling Unit",
      "Sensor Technology": "Diode; VioX - TDi <span class='opt'>(Opt)</span>",
      "Resolution": "Diode 0.4 mm; VioX 0.1 mm",
      "Scanning Speed": "Max. 120 m/min",
      "Drive": "I-Mot3", "Max. Transport Weight": "—",
      "Display": "15\" Color TFT w/ touch screen",
      "Temperature Range": "+5 to +40°C",
      "Construction Frame": "Stainless Steel",
      "IP Rating": "IP65 (Except for Air-Water cooled units)",
      "Power Supply": "230 Vac", "SCCR": "5 kA",
      "Weight": "Approx. 500 kg", "Memory Capacity": "100",
      "Work Height": "750-850 / 800-900 / 850-950 mm",
      "Max. Product Height": "With curtain 246 mm; W/o curtain 303 mm",
      "Transport Length": "2,400 mm"
    }
  },
  {
    brand: "Wipotec",
    name: "SC-S 5020", tag: "Side View",
    image: "img/SC-S-5020.png",
    specs: {
      "Orientation": "Side View", "Output Power": "2 x 500 W",
      "HV Voltage (Infinitely variable)": "Max. 120 kV",
      "HV Current (Infinitely variable)": "Max. 7 mA",
      "Cooling System": "2 x Air-Water Cooling Unit",
      "Sensor Technology": "2 x Diode", "Resolution": "0.4 mm",
      "Scanning Speed": "Max. 120 m/min",
      "Drive": "I-Mot3", "Max. Transport Weight": "—",
      "Display": "15\" Color TFT w/ touch screen; 19\" <span class='opt'>(Opt)</span>",
      "Temperature Range": "+5 to +40°C",
      "Construction Frame": "Stainless Steel",
      "IP Rating": "IP65 (Except for Air-Water cooled units)",
      "Power Supply": "400 Vac 3 Phase", "SCCR": "5 kA",
      "Weight": "Approx. 1,900 kg", "Memory Capacity": "100",
      "Work Height": "750-900 / 800-950 / 900-1050 mm",
      "Max. Product Height": "270 mm; Max dia 140 mm",
      "Transport Length": "Customized"
    }
  }
];

/* ============================================================
   Model data — Mettler-Toledo
   ============================================================ */
const mtWarranty = "• Standard Machine Warranty: 12 Months<br>• Generator Warranty: 5 Years*<br>*Condition: Valid ONLY with purchase of Standard or Comprehensive Care service package (requires annual certified PM). Without active service contract, reverts to standard 12 months.";

const modelsMettlerToledo = [
  { brand: "Mettler-Toledo", name: "X12", tag: "Top-Down", image: "img/X12.png", specs: {
    "Orientation": "Top-Down", "Output Power": "150 W", "HV Voltage (Infinitely variable)": "Up to 84 kV",
    "HV Current (Infinitely variable)": "Up to 3.3 mA", "Cooling System": "Internal Heat Exchanger (Air Cooled)",
    "Sensor Technology": "Diode (HiGain)", "Resolution": "0.4 mm; 0.8 mm <span class='opt'>(Opt)</span>",
    "Scanning Speed": "Max. 60 m/min", "Drive": "Wash down gear motor (Oriental IP67)",
    "Max. Transport Weight": "Up to 10 kg", "Display": "15\" Color TFT Touchscreen",
    "Temperature Range": "+5 to +40°C", "Construction Frame": "Stainless Steel 304",
    "IP Rating": "IP65", "Power Supply": "100 - 240 Vac Single Phase", "SCCR": "NA",
    "Weight": "Approx. 250 - 300 kg", "Memory Capacity": "> 100 products (Unlimited IPC)",
    "Work Height": "750 - 1050 mm", "Max. Product Height": "With overhead reject 180 mm // No reject 220 mm",
    "Transport Length": "800 / 1200 / 1800 mm", "Launch Year": "2023 (Interpack / Sep 2023)",
    "Warranty & Service Contract Conditions": mtWarranty
  }},
  { brand: "Mettler-Toledo", name: "X13", tag: "Top-Down (Bulk Flow)", image: "img/X13.png", specs: {
    "Orientation": "Top-Down (Bulk Flow)", "Output Power": "150 W", "HV Voltage (Infinitely variable)": "Up to 84 kV",
    "HV Current (Infinitely variable)": "Up to 3.3 mA", "Cooling System": "Internal Heat Exchanger (Air Cooled)",
    "Sensor Technology": "Diode (HiGain+)", "Resolution": "0.4 mm; 0.8 mm <span class='opt'>(Opt)</span>",
    "Scanning Speed": "Max. 60 m/min; Mass up to 10,000 kg/hr", "Drive": "Wash down gear motor (Oriental IP67)",
    "Max. Transport Weight": "Mass up to 10,000 kg/hr", "Display": "15\" Color TFT Touchscreen",
    "Temperature Range": "+5 to +40°C", "Construction Frame": "Stainless Steel 304 / 316L",
    "IP Rating": "IP65 (Cabinet) / IP69k (Product zone)", "Power Supply": "100 - 240 Vac Single Phase", "SCCR": "NA",
    "Weight": "Approx. 400 - 500 kg", "Memory Capacity": "> 100 products (Unlimited IPC)",
    "Work Height": "750 - 950 mm", "Max. Product Height": "Bulk height: 20 - 50 mm; Bulk width: 300 - 400 mm",
    "Transport Length": "Approx. 1500 - 1800 mm", "Launch Year": "2025 (Nov 2025 - X3 Series)",
    "Warranty & Service Contract Conditions": mtWarranty
  }},
  { brand: "Mettler-Toledo", name: "X16", tag: "Top-Down", image: "img/X16.png", specs: {
    "Orientation": "Top-Down", "Output Power": "150 W / 420 W", "HV Voltage (Infinitely variable)": "Up to 84 kV",
    "HV Current (Infinitely variable)": "Up to 3.3 mA (100W) / 5.0 mA (420W)", "Cooling System": "Air Cooled (100W); AC Unit & Radiator Pump (420W)",
    "Sensor Technology": "Diode (HiGain+)", "Resolution": "0.4 mm / 0.8 mm",
    "Scanning Speed": "Max. 60 m/min", "Drive": "SEW Geared Motor", "Max. Transport Weight": "Up to 50 kg",
    "Display": "15\" Color TFT Touchscreen", "Temperature Range": "+5 to +40°C",
    "Construction Frame": "Stainless Steel 304", "IP Rating": "IP65 (IP66 / IP69 Opt)",
    "Power Supply": "100 - 240 Vac (100W) / 208 - 240 Vac (420W)", "SCCR": "NA",
    "Weight": "Approx. 450 - 650 kg", "Memory Capacity": "> 100 products (Unlimited IPC)",
    "Work Height": "750 - 1050 mm", "Max. Product Height": "Up to 250 - 300 mm (Aperture width 400 - 600 mm)",
    "Transport Length": "1500 - 2200 mm", "Launch Year": "2024 (Pack Expo Nov 2024)",
    "Warranty & Service Contract Conditions": mtWarranty
  }},
  { brand: "Mettler-Toledo", name: "X34", tag: "Top-Down", image: "img/X34.png", specs: {
    "Orientation": "Top-Down", "Output Power": "100 W (Optimum Power)", "HV Voltage (Infinitely variable)": "Up to 84 kV",
    "HV Current (Infinitely variable)": "Up to 1.2 mA / 3.3 mA", "Cooling System": "Internal Heat Exchanger (Air Cooled)",
    "Sensor Technology": "Diode (HiGain+)", "Resolution": "0.4 mm; 0.8 mm <span class='opt'>(Opt)</span>",
    "Scanning Speed": "Max. 60 m/min", "Drive": "SEW Geared Motor", "Max. Transport Weight": "Up to 10 kg",
    "Display": "10.1\" Touchscreen", "Temperature Range": "+5 to +40°C",
    "Construction Frame": "Stainless Steel 304", "IP Rating": "IP65", "Power Supply": "100 - 240 Vac Single Phase", "SCCR": "NA",
    "Weight": "Approx. 250 - 350 kg", "Memory Capacity": "> 100 products (Unlimited IPC)",
    "Work Height": "750 - 1050 mm", "Max. Product Height": "With overhead reject 150 mm // No reject 180 mm",
    "Transport Length": "800 / 1200 / 1800 mm", "Launch Year": "2018 (Late 2018)",
    "Warranty & Service Contract Conditions": mtWarranty
  }},
  { brand: "Mettler-Toledo", name: "X34C", tag: "Top-Down", image: "img/X34C.png", specs: {
    "Orientation": "Top-Down", "Output Power": "100 W (Optimum Power)", "HV Voltage (Infinitely variable)": "Up to 84 kV",
    "HV Current (Infinitely variable)": "Up to 1.2 mA / 3.3 mA", "Cooling System": "Internal Heat Exchanger (Air Cooled)",
    "Sensor Technology": "Diode (HiGain+)", "Resolution": "0.4 mm",
    "Scanning Speed": "Max. 120 m/min", "Drive": "SEW Geared Motor", "Max. Transport Weight": "Up to 5 kg",
    "Display": "10.1\" Touchscreen", "Temperature Range": "+5 to +40°C",
    "Construction Frame": "Stainless Steel 304", "IP Rating": "IP65", "Power Supply": "100 - 240 Vac Single Phase", "SCCR": "NA",
    "Weight": "Approx. 180 - 220 kg", "Memory Capacity": "> 100 products (Unlimited IPC)",
    "Work Height": "750 - 1050 mm", "Max. Product Height": "Up to 80 - 100 mm", "Transport Length": "700 mm",
    "Launch Year": "2022 (Feb 2022)", "Warranty & Service Contract Conditions": mtWarranty
  }},
  { brand: "Mettler-Toledo", name: "X36", tag: "Top-Down", image: "img/X36.png", specs: {
    "Orientation": "Top-Down", "Output Power": "100 W / 420 W", "HV Voltage (Infinitely variable)": "Up to 84 kV",
    "HV Current (Infinitely variable)": "Up to 3.3 mA (100W) / 3.0 mA (300W) / 5.0 mA (420W)", "Cooling System": "Air Cooled (100W); AC Unit & Radiator Pump (420W)",
    "Sensor Technology": "Diode / Dual Energy (DXD/DXD+ Opt)", "Resolution": "Diode 0.4 mm / 0.8 mm; DXD+ 0.4 mm; DXD 0.8 mm",
    "Scanning Speed": "Max. 100 - 120 m/min (Up to 1,000 ppm)", "Drive": "SEW Geared Motor",
    "Max. Transport Weight": "Up to 25 - 50 kg", "Display": "15.6\" Color TFT Touchscreen",
    "Temperature Range": "+5 to +40°C", "Construction Frame": "Stainless Steel 304 / 316L", "IP Rating": "IP65 (IP69 Opt)",
    "Power Supply": "100 - 240 Vac (208-240 Vac for 420W)", "SCCR": "NA",
    "Weight": "Approx. 400 - 550 kg", "Memory Capacity": "> 100 products (Unlimited IPC)",
    "Work Height": "750 - 1100 mm", "Max. Product Height": "Up to 250 mm (Depending on aperture)",
    "Transport Length": "1200 - 2400 mm / Customized", "Launch Year": "2014 (Interpack 2014)",
    "Warranty & Service Contract Conditions": mtWarranty
  }},
  { brand: "Mettler-Toledo", name: "X36.2", tag: "Top-Down", image: "img/X36.2.png", specs: {
    "Orientation": "Top-Down", "Output Power": "100 W / 420 W", "HV Voltage (Infinitely variable)": "Up to 84 kV",
    "HV Current (Infinitely variable)": "Up to 3.3 mA (100W) / 5.0 mA (420W)", "Cooling System": "Air Cooled (100W); AC Unit & Radiator Pump (420W)",
    "Sensor Technology": "Diode / Dual Energy (DXD Opt)", "Resolution": "0.4 mm / 0.8 mm",
    "Scanning Speed": "Max. 100 - 120 m/min (Single / Multi-lane)", "Drive": "SEW Geared Motor",
    "Max. Transport Weight": "Up to 50 kg", "Display": "15.6\" Color TFT Touchscreen",
    "Temperature Range": "+5 to +40°C", "Construction Frame": "Stainless Steel 304 / 316L", "IP Rating": "IP65 (IP69 Opt)",
    "Power Supply": "100 - 240 Vac (208-240 Vac for 420W)", "SCCR": "NA",
    "Weight": "Approx. 420 - 580 kg", "Memory Capacity": "> 100 products (Unlimited IPC)",
    "Work Height": "750 - 1100 mm", "Max. Product Height": "Up to 250 mm",
    "Transport Length": "1200 - 2400 mm / Customized", "Launch Year": "2024 (Nov 2024)",
    "Warranty & Service Contract Conditions": mtWarranty
  }},
  { brand: "Mettler-Toledo", name: "X36 Bulk", tag: "Top-Down (Bulk Flow)", image: "img/X36.png", specs: {
    "Orientation": "Top-Down (Bulk Flow)", "Output Power": "100 W / 420 W", "HV Voltage (Infinitely variable)": "Up to 84 kV",
    "HV Current (Infinitely variable)": "Up to 3.3 mA (100W) / 5.0 mA (420W)", "Cooling System": "Air Cooled (100W); AC Unit & Radiator Pump (420W)",
    "Sensor Technology": "Diode (HiGain+)", "Resolution": "0.4 mm; 0.8 mm <span class='opt'>(Opt)</span>",
    "Scanning Speed": "Max. 60 m/min; Mass up to 14,000 kg/hr", "Drive": "SEW Geared Motor",
    "Max. Transport Weight": "Bulk mass flow up to 5,000 kg/hr", "Display": "15.6\" Color TFT Touchscreen",
    "Temperature Range": "+5 to +40°C", "Construction Frame": "Stainless Steel 304 / 316L", "IP Rating": "IP65 / IP69k (Product zone)",
    "Power Supply": "100 - 240 Vac Single Phase", "SCCR": "NA",
    "Weight": "Approx. 450 - 550 kg", "Memory Capacity": "> 100 products (Unlimited IPC)",
    "Work Height": "750 - 950 mm", "Max. Product Height": "Bulk height: 20 - 50 mm; Bulk width: 300 - 600 mm",
    "Transport Length": "Approx. 1600 - 2000 mm", "Launch Year": "2015",
    "Warranty & Service Contract Conditions": mtWarranty
  }},
  { brand: "Mettler-Toledo", name: "X52", tag: "Top-Down", image: "img/X52.png", specs: {
    "Orientation": "Top-Down", "Output Power": "100 W (Optimum Power)", "HV Voltage (Infinitely variable)": "Up to 84 kV",
    "HV Current (Infinitely variable)": "Up to 3.3 mA (Beryllium Tube)", "Cooling System": "Air Cooled (Internal heat exchanger)",
    "Sensor Technology": "Dual Energy (HiGain+ DE w/ AMD)", "Resolution": "Dual Energy 0.4 mm / 0.8 mm",
    "Scanning Speed": "Max. 60 - 100 m/min", "Drive": "SEW Geared Motor", "Max. Transport Weight": "Up to 25 kg",
    "Display": "15.6\" Color TFT Touchscreen", "Temperature Range": "+5 to +40°C",
    "Construction Frame": "Stainless Steel 304", "IP Rating": "IP65 (IP66 / IP69 Opt)",
    "Power Supply": "100 - 240 Vac Single Phase", "SCCR": "NA",
    "Weight": "Approx. 350 - 450 kg", "Memory Capacity": "> 100 products (Unlimited IPC)",
    "Work Height": "750 - 1050 mm", "Max. Product Height": "Up to 180 - 200 mm",
    "Transport Length": "800 / 1300 / 1800 / 2000 mm", "Launch Year": "2024 (Oct 2024)",
    "Warranty & Service Contract Conditions": mtWarranty
  }},
  { brand: "Mettler-Toledo", name: "X53", tag: "Top-Down (Bulk Flow)", image: "img/X53.png", specs: {
    "Orientation": "Top-Down (Bulk Flow)", "Output Power": "100 W (Beryllium Tube)", "HV Voltage (Infinitely variable)": "Up to 84 kV",
    "HV Current (Infinitely variable)": "Up to 3.3 mA", "Cooling System": "Air Cooled (Internal heat exchanger)",
    "Sensor Technology": "Dual Energy (HiGain+ DE Technology)", "Resolution": "Dual Energy 0.4 mm / 0.8 mm",
    "Scanning Speed": "Max. 60 - 75 m/min; Mass up to 5,000 kg/hr", "Drive": "SEW Geared Motor",
    "Max. Transport Weight": "Bulk mass flow up to 5,000 kg/hr", "Display": "15.6\" Color TFT Touchscreen",
    "Temperature Range": "+5 to +40°C", "Construction Frame": "Stainless Steel 304 / 316L", "IP Rating": "IP65 / IP69k (Washdown area)",
    "Power Supply": "100 - 240 Vac Single Phase", "SCCR": "NA",
    "Weight": "Approx. 450 - 550 kg", "Memory Capacity": "> 100 products (Unlimited IPC)",
    "Work Height": "750 - 950 mm", "Max. Product Height": "Bulk layer: 20 - 50 mm; Belt width: 300 - 400 mm",
    "Transport Length": "Approx. 1500 - 1800 mm", "Launch Year": "2025 (Nov 2025 - X3 Series DE)",
    "Warranty & Service Contract Conditions": mtWarranty
  }},
  { brand: "Mettler-Toledo", name: "X56", tag: "Top-Down", image: "img/X56.png", specs: {
    "Orientation": "Top-Down", "Output Power": "420 W", "HV Voltage (Infinitely variable)": "Up to 84 kV",
    "HV Current (Infinitely variable)": "Up to 5.0 mA (Beryllium Tube)", "Cooling System": "Air Conditioner & Radiator Pump (Closed loop)",
    "Sensor Technology": "Dual Energy Photon-Counting (DXD+ w/ AI & AMD Pro)", "Resolution": "Dual Energy 0.4 mm / 0.8 mm",
    "Scanning Speed": "Max. 100 - 120 m/min (Throughput up to 500 ppm)", "Drive": "SEW Geared Motor",
    "Max. Transport Weight": "Up to 50 kg", "Display": "15.6\" Color TFT Touchscreen",
    "Temperature Range": "+5 to +40°C", "Construction Frame": "Stainless Steel 304 / 316L", "IP Rating": "IP65 / IP66 (IP69 Opt)",
    "Power Supply": "208 - 240 Vac Single Phase", "SCCR": "NA",
    "Weight": "Approx. 550 - 750 kg", "Memory Capacity": "> 100 products (Unlimited IPC)",
    "Work Height": "750 - 1050 mm", "Max. Product Height": "Up to 250 - 300 mm (Max product width 480 mm)",
    "Transport Length": "1500 - 2400 mm / Customized", "Launch Year": "2026 (Jun 2026)",
    "Warranty & Service Contract Conditions": mtWarranty
  }},
  { brand: "Mettler-Toledo", name: "X3710", tag: "Side View (Single Horizontal Beam)", image: "img/X3710.png", specs: {
    "Orientation": "Side View (Single Horizontal Beam)", "Output Power": "20 W (Low-Power Generator)",
    "HV Voltage (Infinitely variable)": "Up to 84 kV", "HV Current (Infinitely variable)": "Up to 0.25 mA (Glass Tube)",
    "Cooling System": "Passive fan assisted internal cooling", "Sensor Technology": "Diode (HiGain Technology)",
    "Resolution": "0.8 mm", "Scanning Speed": "Max. 60 - 90 m/min (Up to 600 ppm)",
    "Drive": "Customer line conveyor (Line straddling)", "Max. Transport Weight": "N/A (Continuous container line)",
    "Display": "15.6\" Color TFT Touchscreen", "Temperature Range": "+5 to +40°C",
    "Construction Frame": "Stainless Steel 304", "IP Rating": "IP65 (IP69 Opt)",
    "Power Supply": "100 - 240 Vac Single Phase", "SCCR": "NA",
    "Weight": "Approx. 300 - 400 kg", "Memory Capacity": "> 100 products (Unlimited IPC)",
    "Work Height": "750 - 1100 mm", "Max. Product Height": "Up to 280 mm",
    "Transport Length": "Straddles customer conveyor (~1200 - 1500 mm tunnel)",
    "Launch Year": "2015 (Jan 2015)", "Warranty & Service Contract Conditions": mtWarranty
  }},
  { brand: "Mettler-Toledo", name: "X3720", tag: "Side View (Single Horizontal Beam)", image: "img/X3720.png", specs: {
    "Orientation": "Side View (Single Horizontal Beam)", "Output Power": "100 W",
    "HV Voltage (Infinitely variable)": "Up to 84 kV", "HV Current (Infinitely variable)": "Up to 1.2 mA (100W)",
    "Cooling System": "AC Unit", "Sensor Technology": "Diode (Single Beam 400mm detector)",
    "Resolution": "0.8 mm", "Scanning Speed": "Max. 120 m/min (Up to 1,200 ppm)",
    "Drive": "Customer line conveyor (Straddling design)", "Max. Transport Weight": "N/A (Continuous container line)",
    "Display": "15.6\" Color TFT Touchscreen", "Temperature Range": "+5 to +40°C",
    "Construction Frame": "Stainless Steel 304 (316L Opt)", "IP Rating": "IP65 (IP69 Opt)",
    "Power Supply": "100 - 240 Vac Single Phase", "SCCR": "NA",
    "Weight": "Approx. 400 - 500 kg", "Memory Capacity": "> 100 products (Unlimited IPC)",
    "Work Height": "750 - 1150 mm", "Max. Product Height": "Up to 270 mm (Tall cans, plastics)",
    "Transport Length": "Approx. 1200 - 1800 mm (Line straddling)",
    "Launch Year": "2015 (Jan 2015)", "Warranty & Service Contract Conditions": mtWarranty
  }},
  { brand: "Mettler-Toledo", name: "X3725", tag: "Side View (Single Horizontal Beam)", image: "img/X3725.png", specs: {
    "Orientation": "Side View (Single Horizontal Beam)", "Output Power": "100 W",
    "HV Voltage (Infinitely variable)": "Up to 84 kV", "HV Current (Infinitely variable)": "Up to 1.2 mA (100W)",
    "Cooling System": "AC Unit", "Sensor Technology": "Diode (Single Beam 400mm detector)",
    "Resolution": "0.8 mm", "Scanning Speed": "Max. 120 m/min (Up to 1,200 ppm)",
    "Drive": "Integrated full-length slat conveyor w/ guide rails", "Max. Transport Weight": "N/A (Continuous container line)",
    "Display": "15.6\" Color TFT Touchscreen", "Temperature Range": "+5 to +40°C",
    "Construction Frame": "Stainless Steel 304 (316L Opt)", "IP Rating": "IP65 (IP69 Opt)",
    "Power Supply": "100 - 240 Vac Single Phase", "SCCR": "NA",
    "Weight": "Approx. 550 - 700 kg", "Memory Capacity": "> 100 products (Unlimited IPC)",
    "Work Height": "950 / 1050 / 1150 mm (+/- 50 mm)", "Max. Product Height": "Up to 270 - 280 mm (Diameter up to 188 mm)",
    "Transport Length": "4,500 - 5,200 mm (Full-length integrated conveyor)",
    "Launch Year": "2015 (Mid 2015)", "Warranty & Service Contract Conditions": mtWarranty
  }},
  { brand: "Mettler-Toledo", name: "X3730", tag: "Side View (Split-Beam)", image: "img/X3730.png", specs: {
    "Orientation": "Side View (Split-Beam)", "Output Power": "420 W",
    "HV Voltage (Infinitely variable)": "Up to 84 kV", "HV Current (Infinitely variable)": "Up to 5.0 mA (420W)",
    "Cooling System": "AC Unit & Radiator Pump (420W)", "Sensor Technology": "Diode (Split-Beam Dual Detector)",
    "Resolution": "0.8 mm", "Scanning Speed": "Max. 120 m/min (Up to 1,200 ppm)",
    "Drive": "Customer line conveyor (Straddling design)", "Max. Transport Weight": "N/A (Continuous container line)",
    "Display": "15.6\" Color TFT Touchscreen", "Temperature Range": "+5 to +40°C",
    "Construction Frame": "Stainless Steel 304 (316L Opt)", "IP Rating": "IP65 (IP69 Opt)",
    "Power Supply": "100 - 240 Vac (208-240 Vac for 420W)", "SCCR": "NA",
    "Weight": "Approx. 450 - 600 kg", "Memory Capacity": "> 100 products (Unlimited IPC)",
    "Work Height": "750 - 1150 mm", "Max. Product Height": "Up to 270 mm (Glass / metal cans)",
    "Transport Length": "Approx. 1800 - 2400 mm (Line straddling)",
    "Launch Year": "2015 (Jan 2015)", "Warranty & Service Contract Conditions": mtWarranty
  }},
  { brand: "Mettler-Toledo", name: "X3735", tag: "Side View (Split-Beam)", image: "img/X3735.png", specs: {
    "Orientation": "Side View (Split-Beam)", "Output Power": "420 W",
    "HV Voltage (Infinitely variable)": "Up to 84 kV", "HV Current (Infinitely variable)": "Up to 5.0 mA (420W)",
    "Cooling System": "AC Unit & Radiator Pump (420W)", "Sensor Technology": "Diode (Split-Beam Dual Detector)",
    "Resolution": "0.8 mm", "Scanning Speed": "Max. 120 m/min (Up to 1,200 ppm)",
    "Drive": "Integrated full-length slat conveyor w/ guide rails", "Max. Transport Weight": "N/A (Continuous container line)",
    "Display": "15.6\" Color TFT Touchscreen", "Temperature Range": "+5 to +40°C",
    "Construction Frame": "Stainless Steel 304 (316L Opt)", "IP Rating": "IP65 (IP69 Opt)",
    "Power Supply": "100 - 240 Vac (208-240 Vac for 420W)", "SCCR": "NA",
    "Weight": "Approx. 600 - 750 kg", "Memory Capacity": "> 100 products (Unlimited IPC)",
    "Work Height": "950 / 1050 / 1150 mm (+/- 50 mm)", "Max. Product Height": "Up to 270 - 280 mm",
    "Transport Length": "4,500 - 5,200 mm (Full-length integrated conveyor)",
    "Launch Year": "2015 (Mid 2015)", "Warranty & Service Contract Conditions": mtWarranty
  }},
  { brand: "Mettler-Toledo", name: "X3750", tag: "Side View (Angle Beam)", image: "img/X3750.png", specs: {
    "Orientation": "Side View (Angle Beam)", "Output Power": "420 W",
    "HV Voltage (Infinitely variable)": "Up to 84 kV or 100 kV", "HV Current (Infinitely variable)": "Up to 5.0 mA (420W)",
    "Cooling System": "AC Unit & Radiator Pump (420W)", "Sensor Technology": "Angle Beam Detector",
    "Resolution": "0.4 mm / 0.8 mm", "Scanning Speed": "Max. 120 m/min (Up to 800 - 1,200 bpm)",
    "Drive": "Integrated conveyor", "Max. Transport Weight": "N/A (Continuous glass container line)",
    "Display": "15.6\" Color TFT Touchscreen", "Temperature Range": "+5 to +40°C",
    "Construction Frame": "Stainless Steel 304 / 316L", "IP Rating": "IP65 (IP69 Opt)",
    "Power Supply": "208-240 Vac for 420W", "SCCR": "NA",
    "Weight": "Approx. 1,000 - 1,400 kg", "Memory Capacity": "> 100 products (Unlimited IPC)",
    "Work Height": "950 / 1050 / 1150 mm (+/- 50 mm)", "Max. Product Height": "Up to 270 - 300 mm (Max jar dia 130 - 150 mm)",
    "Transport Length": "4,500 - 5,200 mm (Full-length integrated conveyor)",
    "Launch Year": "2016 (Mar 2016 Glass-in-Glass)", "Warranty & Service Contract Conditions": mtWarranty
  }}
];

/* ============================================================
   Model data — Ishida
   ============================================================ */
const modelsIshida = [
  { brand: "Ishida", name: "IX-EN-2463", tag: "Top-Down", image: "img/IX-EN.png", specs: {
    "Orientation": "Top-Down", "Output Power": "Max. 50 W", "HV Voltage (Infinitely variable)": "30/35/40/45/50 kV",
    "HV Current (Infinitely variable)": "1 mA", "Cooling System": "Heat Sink (Standard)",
    "Sensor Technology": "Standard X-ray", "Resolution": "0.4 mm",
    "Scanning Speed": "10-60 m/min (90 m/min optional)", "Drive": "—", "Max. Transport Weight": "5 kg",
    "Display": "15\" Touch Panel", "Temperature Range": "0 to +33°C",
    "Construction Frame": "Stainless Steel SUS304 (Polished)", "IP Rating": "IP66 (Conveyor Chamber) / IP54 (Enclosure)",
    "Power Supply": "Single-phase AC 200-240V, 50/60 Hz, 450W", "SCCR": "—",
    "Weight": "250 kg", "Memory Capacity": "—",
    "Work Height": "900 mm ± 50", "Max. Product Height": "150 mm",
    "Transport Length": "800 × 270 mm"
  }},
  { brand: "Ishida", name: "IX-EN-2493", tag: "Top-Down", image: "img/IX-EN.png", specs: {
    "Orientation": "Top-Down", "Output Power": "Max. 150 W", "HV Voltage (Infinitely variable)": "30/35/40/45/50/55/60/65/70/75 kV",
    "HV Current (Infinitely variable)": "1-3 mA", "Cooling System": "Heat Sink (Standard)",
    "Sensor Technology": "Standard X-ray", "Resolution": "0.4 mm",
    "Scanning Speed": "10-60 m/min (90 m/min optional)", "Drive": "—", "Max. Transport Weight": "5 kg",
    "Display": "15\" Touch Panel", "Temperature Range": "0 to +33°C",
    "Construction Frame": "Stainless Steel SUS304 (Polished)", "IP Rating": "IP66 (Conveyor Chamber) / IP54 (Enclosure)",
    "Power Supply": "Single-phase AC 200-240V, 50/60 Hz, 500W", "SCCR": "—",
    "Weight": "265 kg", "Memory Capacity": "—",
    "Work Height": "900 mm ± 50", "Max. Product Height": "150 mm",
    "Transport Length": "800 × 270 mm"
  }},
  { brand: "Ishida", name: "IX-EN-2493-C", tag: "Top-Down (Compact)", image: "img/IX-EN-2493-C.png", specs: {
    "Orientation": "Top-Down (Compact)", "Output Power": "Max. 150 W", "HV Voltage (Infinitely variable)": "30/35/40/45/50/55/60/65/70/75 kV",
    "HV Current (Infinitely variable)": "1-3 mA", "Cooling System": "Heat Sink (Standard)",
    "Sensor Technology": "Standard X-ray", "Resolution": "0.4 mm",
    "Scanning Speed": "10-120 m/min", "Drive": "—", "Max. Transport Weight": "5 kg",
    "Display": "15\" Touch Panel", "Temperature Range": "0 to +33°C",
    "Construction Frame": "Stainless Steel SUS304 (Polished)", "IP Rating": "IP66 (Conveyor Chamber) / IP54 (Enclosure)",
    "Power Supply": "Single-phase AC 200-240V, 50/60 Hz, 500W", "SCCR": "—",
    "Weight": "265 kg", "Memory Capacity": "—",
    "Work Height": "900 mm ± 50", "Max. Product Height": "30 mm",
    "Transport Length": "1115 × 160 mm"
  }},
  { brand: "Ishida", name: "IX-EN-24A1", tag: "Top-Down", image: "img/IX-EN-24A1.png", specs: {
    "Orientation": "Top-Down", "Output Power": "Max. 150 W", "HV Voltage (Infinitely variable)": "25-75 kV",
    "HV Current (Infinitely variable)": "1-5 mA", "Cooling System": "Heat Sink (Standard)",
    "Sensor Technology": "GA Auto Choice (300 programs)", "Resolution": "—",
    "Scanning Speed": "10-60 m/min", "Drive": "—", "Max. Transport Weight": "5 kg",
    "Display": "15\" Touch Panel", "Temperature Range": "0 to +33°C",
    "Construction Frame": "Stainless Steel SUS304 (Polished)", "IP Rating": "IP66 (Inspection Chamber)",
    "Power Supply": "Single-phase AC 200V, 500W, 3.0A", "SCCR": "—",
    "Weight": "265 kg", "Memory Capacity": "200 items",
    "Work Height": "900 mm ± 50", "Max. Product Height": "150 mm",
    "Transport Length": "800 × 270 mm",
    "Warranty & Service Contract Conditions": "X-ray tube + line sensor: 15,000 hours or 3 years (whichever comes first)"
  }},
  { brand: "Ishida", name: "IX-EN-4062", tag: "Top-Down", image: "img/IX-EN.png", specs: {
    "Orientation": "Top-Down", "Output Power": "Max. 55 W", "HV Voltage (Infinitely variable)": "30/35/40/45/50/55 kV",
    "HV Current (Infinitely variable)": "1 mA", "Cooling System": "Heat Sink (Standard)",
    "Sensor Technology": "Standard X-ray", "Resolution": "0.6 mm",
    "Scanning Speed": "10-60 m/min", "Drive": "—", "Max. Transport Weight": "5 kg",
    "Display": "15\" Touch Panel", "Temperature Range": "0 to +33°C",
    "Construction Frame": "Stainless Steel SUS304 (Polished)", "IP Rating": "IP66 (Conveyor Chamber) / IP54 (Enclosure)",
    "Power Supply": "Single-phase AC 200-240V, 50/60 Hz, 450W", "SCCR": "—",
    "Weight": "290 kg", "Memory Capacity": "—",
    "Work Height": "900 mm ± 50", "Max. Product Height": "150 mm",
    "Transport Length": "800 × 430 mm"
  }},
  { brand: "Ishida", name: "IX-EN-4093", tag: "Top-Down", image: "img/IX-EN.png", specs: {
    "Orientation": "Top-Down", "Output Power": "Max. 150 W", "HV Voltage (Infinitely variable)": "30/35/40/45/50/55/60/65/70/75 kV",
    "HV Current (Infinitely variable)": "1-3 mA", "Cooling System": "Heat Sink (Standard)",
    "Sensor Technology": "Standard X-ray", "Resolution": "0.4 mm",
    "Scanning Speed": "10-60 m/min", "Drive": "—", "Max. Transport Weight": "5 kg",
    "Display": "15\" Touch Panel", "Temperature Range": "0 to +33°C",
    "Construction Frame": "Stainless Steel SUS304 (Polished)", "IP Rating": "IP66 (Conveyor Chamber) / IP54 (Enclosure)",
    "Power Supply": "Single-phase AC 200-240V, 50/60 Hz, 500W", "SCCR": "—",
    "Weight": "290 kg", "Memory Capacity": "—",
    "Work Height": "900 mm ± 50", "Max. Product Height": "150 mm",
    "Transport Length": "800 × 430 mm"
  }},
  { brand: "Ishida", name: "IX-EN-5592", tag: "Top-Down (Large)", image: "img/IX-EN-5592.png", specs: {
    "Orientation": "Top-Down (Large)", "Output Power": "Max. 150 W", "HV Voltage (Infinitely variable)": "30-90 kV",
    "HV Current (Infinitely variable)": "1.0-3.0 mA", "Cooling System": "Hermetic Air Cooling",
    "Sensor Technology": "GA (Genetic Algorithm)", "Resolution": "—",
    "Scanning Speed": "5-30 m/min (25 kg) / 10-60 m/min (5 kg)", "Drive": "—", "Max. Transport Weight": "25 kg",
    "Display": "15\" Color Touch Display", "Temperature Range": "0 to +33°C",
    "Construction Frame": "Stainless Steel 304", "IP Rating": "IP66 (Conveyor) / IP54 (Enclosure, IP65 opt)",
    "Power Supply": "Single-phase AC 200-240V, 50/60Hz, 1150W", "SCCR": "—",
    "Weight": "500 kg", "Memory Capacity": "—",
    "Work Height": "750 mm ± 50", "Max. Product Height": "270 mm",
    "Transport Length": "1200 × 600 mm"
  }},
  { brand: "Ishida", name: "IX-GN-2443", tag: "Top-Down", image: "img/IX-GN-2443.png", specs: {
    "Orientation": "Top-Down", "Output Power": "Max. 150 W", "HV Voltage (Infinitely variable)": "25/30/35/40/45/50/55/60/65/70/75 kV",
    "HV Current (Infinitely variable)": "1-5 mA", "Cooling System": "Integrated Air Conditioning",
    "Sensor Technology": "GA (Genetic Algorithm)", "Resolution": "0.4 mm",
    "Scanning Speed": "10-60 m/min (90 m/min optional)", "Drive": "—", "Max. Transport Weight": "5 kg",
    "Display": "17\" Touch Screen", "Temperature Range": "0 to +35°C",
    "Construction Frame": "Stainless Steel SUS304 (Polished)", "IP Rating": "IP66 (Conveyor Chamber) / IP65 (Enclosure)",
    "Power Supply": "Single-phase AC 200-240V, 50/60 Hz, 1000W (1150W)", "SCCR": "—",
    "Weight": "285 kg", "Memory Capacity": "—",
    "Work Height": "900 mm ± 50", "Max. Product Height": "150 mm",
    "Transport Length": "800 × 270 mm"
  }},
  { brand: "Ishida", name: "IX-GN-2444", tag: "Top-Down", image: "img/IX-GN-2443.png", specs: {
    "Orientation": "Top-Down", "Output Power": "Max. 300 W", "HV Voltage (Infinitely variable)": "25/30/35/40/45/50/55/60/65/70/75 kV",
    "HV Current (Infinitely variable)": "1-8 mA", "Cooling System": "Integrated Air Conditioning",
    "Sensor Technology": "GA (Genetic Algorithm)", "Resolution": "0.3 mm",
    "Scanning Speed": "10-60 m/min (90 m/min optional)", "Drive": "—", "Max. Transport Weight": "5 kg",
    "Display": "17\" Touch Screen", "Temperature Range": "0 to +35°C",
    "Construction Frame": "Stainless Steel SUS304 (Polished)", "IP Rating": "IP66 (Conveyor Chamber) / IP65 (Enclosure)",
    "Power Supply": "Single-phase AC 200-240V, 50/60 Hz, 1150W", "SCCR": "—",
    "Weight": "285 kg", "Memory Capacity": "—",
    "Work Height": "900 mm ± 50", "Max. Product Height": "150 mm",
    "Transport Length": "800 × 270 mm"
  }},
  { brand: "Ishida", name: "IX-GN-4043", tag: "Top-Down", image: "img/IX-GN.png", specs: {
    "Orientation": "Top-Down", "Output Power": "Max. 150 W", "HV Voltage (Infinitely variable)": "25/30/35/40/45/50/55/60/65/70/75 kV",
    "HV Current (Infinitely variable)": "1-5 mA", "Cooling System": "Integrated Air Conditioning",
    "Sensor Technology": "GA (Genetic Algorithm)", "Resolution": "0.4 mm",
    "Scanning Speed": "10-60 m/min", "Drive": "—", "Max. Transport Weight": "5 kg",
    "Display": "17\" Touch Screen", "Temperature Range": "0 to +35°C",
    "Construction Frame": "Stainless Steel SUS304 (Polished)", "IP Rating": "IP66 (Conveyor Chamber) / IP65 (Enclosure)",
    "Power Supply": "Single-phase AC 200-240V, 50/60 Hz, 1000W (1150W)", "SCCR": "—",
    "Weight": "315 kg", "Memory Capacity": "—",
    "Work Height": "900 mm ± 50", "Max. Product Height": "150 mm",
    "Transport Length": "800 × 430 mm"
  }},
  { brand: "Ishida", name: "IX-GN-4044", tag: "Top-Down", image: "img/IX-GN.png", specs: {
    "Orientation": "Top-Down", "Output Power": "Max. 300 W", "HV Voltage (Infinitely variable)": "25/30/35/40/45/50/55/60/65/70/75 kV",
    "HV Current (Infinitely variable)": "1-8 mA", "Cooling System": "Integrated Air Conditioning",
    "Sensor Technology": "GA (Genetic Algorithm)", "Resolution": "0.3 mm",
    "Scanning Speed": "10-60 m/min", "Drive": "—", "Max. Transport Weight": "5 kg",
    "Display": "17\" Touch Screen", "Temperature Range": "0 to +35°C",
    "Construction Frame": "Stainless Steel SUS304 (Polished)", "IP Rating": "IP66 (Conveyor Chamber) / IP65 (Enclosure)",
    "Power Supply": "Single-phase AC 200-240V, 50/60 Hz, 1150W", "SCCR": "—",
    "Weight": "315 kg", "Memory Capacity": "—",
    "Work Height": "900 mm ± 50", "Max. Product Height": "150 mm",
    "Transport Length": "800 × 430 mm"
  }},
  { brand: "Ishida", name: "IX-GN-4044A", tag: "Top-Down", image: "img/IX-GN.png", specs: {
    "Orientation": "Top-Down", "Output Power": "Max. 300 W", "HV Voltage (Infinitely variable)": "25/30/35/40/45/50/55/60/65/70/75 kV",
    "HV Current (Infinitely variable)": "1-8 mA", "Cooling System": "Integrated Air Conditioning",
    "Sensor Technology": "GA (Genetic Algorithm)", "Resolution": "0.3 mm",
    "Scanning Speed": "10-60 m/min", "Drive": "—", "Max. Transport Weight": "5 kg",
    "Display": "17\" Touch Screen", "Temperature Range": "0 to +35°C",
    "Construction Frame": "Stainless Steel SUS304 (Polished)", "IP Rating": "IP66 (Conveyor Chamber) / IP65 (Enclosure)",
    "Power Supply": "Single-phase AC 200-240V, 50/60 Hz, 1150W", "SCCR": "—",
    "Weight": "315 kg", "Memory Capacity": "—",
    "Work Height": "900 mm ± 50", "Max. Product Height": "220 mm",
    "Transport Length": "800 × 430 mm"
  }},
  { brand: "Ishida", name: "IX-GN-5523", tag: "Top-Down (Large)", image: "img/IX-GN.png", specs: {
    "Orientation": "Top-Down (Large)", "Output Power": "Max. 350 W", "HV Voltage (Infinitely variable)": "40-100 kV",
    "HV Current (Infinitely variable)": "1-5 mA", "Cooling System": "Integrated Air Conditioning",
    "Sensor Technology": "GA (Genetic Algorithm)", "Resolution": "0.4 mm",
    "Scanning Speed": "5-30 m/min (optional 10-60 m/min)", "Drive": "—", "Max. Transport Weight": "25 kg (30 kg optional)",
    "Display": "17\" Touch Screen", "Temperature Range": "0 to +35°C",
    "Construction Frame": "Stainless Steel SUS304 (Polished)", "IP Rating": "IP66 (Conveyor Chamber) / IP54 (Enclosure)",
    "Power Supply": "Single-phase AC 200-240V, 50/60Hz, 12A, 1900W", "SCCR": "—",
    "Weight": "500 kg", "Memory Capacity": "—",
    "Work Height": "900 mm ± 50", "Max. Product Height": "270 mm",
    "Transport Length": "1200 × 600 mm"
  }},
  { brand: "Ishida", name: "IX-G2-2427", tag: "Top-Down (Dual Energy)", image: "img/IX-G2.png", specs: {
    "Orientation": "Top-Down", "Output Power": "Max. 350 W", "HV Voltage (Infinitely variable)": "Max. 100 kV",
    "HV Current (Infinitely variable)": "Max. 5 mA", "Cooling System": "Hermetic Air Cooling",
    "Sensor Technology": "Dual Energy Sensor (G2 Technology)", "Resolution": "0.4 mm",
    "Scanning Speed": "10-60 m/min", "Drive": "—", "Max. Transport Weight": "Max. 5 kg",
    "Display": "17\" TFT LCD Touch Screen (Windows XP)", "Temperature Range": "0 to +35°C",
    "Construction Frame": "Stainless Steel SUS304 (Bead Blast Finish)", "IP Rating": "IP66 (Conveyor Room) / IP65 (Outside)",
    "Power Supply": "Single-phase AC 200-240V, 50/60 Hz, ±10%", "SCCR": "—",
    "Weight": "360 kg", "Memory Capacity": "100 items (expandable)",
    "Work Height": "900 mm ± 50", "Max. Product Height": "150 mm",
    "Transport Length": "800 × 270 mm"
  }},
  { brand: "Ishida", name: "IX-G2-4027", tag: "Top-Down (Dual Energy)", image: "img/IX-G2.png", specs: {
    "Orientation": "Top-Down", "Output Power": "Max. 350 W", "HV Voltage (Infinitely variable)": "Max. 100 kV",
    "HV Current (Infinitely variable)": "Max. 5 mA", "Cooling System": "Hermetic Air Cooling",
    "Sensor Technology": "Dual Energy Sensor (G2 Technology)", "Resolution": "0.4 mm",
    "Scanning Speed": "10-60 m/min", "Drive": "—", "Max. Transport Weight": "Max. 5 kg",
    "Display": "17\" TFT LCD Touch Screen (Windows XP)", "Temperature Range": "0 to +35°C",
    "Construction Frame": "Stainless Steel SUS304 (Bead Blast Finish)", "IP Rating": "IP66 (Conveyor Room) / IP65 (Outside)",
    "Power Supply": "Single-phase AC 200-240V, 50/60 Hz, ±10%", "SCCR": "—",
    "Weight": "400 kg", "Memory Capacity": "100 items (expandable)",
    "Work Height": "900 mm ± 50", "Max. Product Height": "150 mm",
    "Transport Length": "800 × 430 mm"
  }},
  { brand: "Ishida", name: "IX-PD-36A2", tag: "Top-Down (Photon Counting)", image: "img/IX-PD.png", specs: {
    "Orientation": "Top-Down", "Output Power": "Max. 300 W", "HV Voltage (Infinitely variable)": "25-75 kV",
    "HV Current (Infinitely variable)": "1-8 mA", "Cooling System": "1.0kW Air Conditioner (Built-in)",
    "Sensor Technology": "Photon Counting Dual Energy (Direct Conversion)", "Resolution": "—",
    "Scanning Speed": "10-60 m/min", "Drive": "—", "Max. Transport Weight": "5 kg",
    "Display": "17\" Color LCD Touch Panel", "Temperature Range": "0 to +35°C",
    "Construction Frame": "Stainless Steel", "IP Rating": "IP66",
    "Power Supply": "Single-phase AC 200-240V, 1400W (8.0A at AC200V)", "SCCR": "—",
    "Weight": "Approx. 340 kg", "Memory Capacity": "100 items",
    "Work Height": "750 mm ± 50", "Max. Product Height": "150 mm",
    "Transport Length": "—"
  }},
  { brand: "Ishida", name: "IX-PD-45A2", tag: "Top-Down (Photon Counting)", image: "img/IX-PD.png", specs: {
    "Orientation": "Top-Down", "Output Power": "Max. 300 W", "HV Voltage (Infinitely variable)": "25-75 kV",
    "HV Current (Infinitely variable)": "1-8 mA", "Cooling System": "1.0kW Air Conditioner (Built-in)",
    "Sensor Technology": "Photon Counting Dual Energy (Direct Conversion)", "Resolution": "—",
    "Scanning Speed": "10-48 m/min", "Drive": "—", "Max. Transport Weight": "5 kg",
    "Display": "17\" Color LCD Touch Panel", "Temperature Range": "0 to +35°C",
    "Construction Frame": "Stainless Steel", "IP Rating": "IP66",
    "Power Supply": "Single-phase AC 200-240V, 1400W (8.0A at AC200V)", "SCCR": "—",
    "Weight": "Approx. 370 kg", "Memory Capacity": "100 items",
    "Work Height": "750 mm ± 50", "Max. Product Height": "150 mm",
    "Transport Length": "—"
  }},
  { brand: "Ishida", name: "IX-GA-65100", tag: "Top-Down (Large High)", image: "img/IX-GA-65100.png", specs: {
    "Orientation": "Top-Down (Large High)", "Output Power": "Max. 350 W", "HV Voltage (Infinitely variable)": "40/45/50/55/60/65/70/75/80/85/90/95/100 kV",
    "HV Current (Infinitely variable)": "1-5.0 mA", "Cooling System": "Hermetic Air Cooling",
    "Sensor Technology": "GA (Genetic Algorithm)", "Resolution": "—",
    "Scanning Speed": "5-30 m/min", "Drive": "—", "Max. Transport Weight": "Max. 50 kg",
    "Display": "Color Touchscreen", "Temperature Range": "0 to +40°C",
    "Construction Frame": "Stainless Steel", "IP Rating": "IP65 (Conveyor: IP66)",
    "Power Supply": "AC 200/208/220/230/240V, 50/60 Hz, ±10%", "SCCR": "—",
    "Weight": "—", "Memory Capacity": "—",
    "Work Height": "750 mm ± 50", "Max. Product Height": "270 mm (Option: 420 mm)",
    "Transport Length": "1200 × 700 mm"
  }},
  { brand: "Ishida", name: "IX-GA-B3043", tag: "Side View (Bottle)", image: "img/IX-GA-B3043.png", specs: {
    "Orientation": "Side View (Bottle)", "Output Power": "Max. 300 W", "HV Voltage (Infinitely variable)": "30-75 kV",
    "HV Current (Infinitely variable)": "1-8.0 mA", "Cooling System": "Hermetic Air Cooling",
    "Sensor Technology": "GA (Genetic Algorithm)", "Resolution": "—",
    "Scanning Speed": "12-45 m/min (10kg) / 4-40 m/min (5kg)", "Drive": "Turn Table (Circular)",
    "Max. Transport Weight": "—", "Display": "Color Touchscreen",
    "Temperature Range": "0 to +40°C", "Construction Frame": "Stainless Steel",
    "IP Rating": "IP65 / IP66 (Conveyor Unit)",
    "Power Supply": "Single-phase AC 200-240V, 50/60 Hz", "SCCR": "—",
    "Weight": "—", "Memory Capacity": "—",
    "Work Height": "—", "Max. Product Height": "310 mm",
    "Transport Length": "1550 × 1685 mm"
  }}
];

/* ============================================================
   All models combined
   ============================================================ */
const allModels = [...modelsWipotec, ...modelsMettlerToledo, ...modelsIshida];
const models = allModels;